[[ -o interactive ]] || return 0

source "${WORKSTATION_ZSH_DIR}/lib/zshrc-helpers.zsh"
source_if_exists "${WORKSTATION_ZSH_DIR}/lib/history.zsh"
source_if_exists "${WORKSTATION_ZSH_DIR}/lib/oh-my-zsh.zsh"
source_if_exists "${WORKSTATION_ZSH_DIR}/lib/aliases.zsh"
source_if_exists "${WORKSTATION_ZSH_DIR}/lib/python-venv.zsh"
source_if_exists "${WORKSTATION_ZSH_DIR}/lib/integrations.zsh"
